language: java
jdk:
- oraclejdk8
addons:
  srcclr: true
  apt:
    packages:
    - oracle-java8-installer
    - maven
cache:
  directories:
  - "$HOME/.m2"
install: mvn -v
script: mvn package
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
deploy:
  provider: heroku
  app: vatbubgitreports
  skip_cleanup: true
  on:
    repo: vatbub/vatbubgitreports2
  api_key:
    secure: OUe+/4aeZgmjTUOpuSLlI0t44xL0QWh5x2IdsDtKl/Mj69dzSj74AuLcOEY/z9ilJv8oXIuQx3l/Quyavy4IgOb7QJcKnPB+RN5rZW90yoF6cyebcIHCySl53Ee3Yntxle2W6r6q6ivWWlApL3NmmvhYeqXgp/uyMr4xUzngNdTs6aGhMi9ujWgWFtZHLjzjgQy3TNqNCf92mKT3cY9FtBd9vYWZRacpJsbAdMtEh2n8BoqbsVTLzqdtvYBwVA/LbhtRYN9VmRD/PzzgZUMGcfvnvBLbKxT/5ET2lmXsThtf4Xhylqdu4JlmiCwST54Fw/PTjbX+NIVosDrqJGgGkAN8FXeueLFLNd1IKgWots+mrtpqZ8ZokXB0fxCKgP3PY2LHK2FZfUf9WfGJMUJKyOetMq+Rz1RgjJjVqGnwvnc3oPCDdzwD9VVvZzsaawGKz5oNRy8h1Re/HxRQUywu+M/e1VPl72Du06J2VCjpFG9GPweatgs92XX9Ogg/PRd0r4Tige3qbNgR3/WOGZ3upEJoTU+7CNsfd69kY+48Oy3ZVToRkGSNpOdqYHNNbPfi1XpDiGfKe5YoT2h4qXfObT9+tPfUvn78jHL5bSVuRj7vXeaH/ozXyvPZTPwFxmXARX0ReE9VgAhGyrpWIVwPG6AXW+ChutHLDntvaTuhU4k=
